#!/usr/bin/env python3
"""
OpenAI Batch API runner for survey simulation.

Workflow:
  1. submit  – generate prompts, upload batch file, create batch job
  2. fetch   – poll status; download + parse results when complete

Usage:
    # Submit a wave
    python batch_api_runner.py submit --wave 26 --model gpt-4o --api-key sk-...

    # Check status / fetch results (use batch_id printed at submit time)
    python batch_api_runner.py fetch --batch-id batch_abc123 --wave 26 --model gpt-4o --api-key sk-...

Output:
    data/results/{model}/W{wave}.jsonl  (same format as existing pipeline)
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import datetime
from itertools import combinations, product
from pathlib import Path

import openai

sys.path.insert(0, os.path.dirname(__file__))
from llm_prompt_survey import DemographicProfile, PromptBuilder, ResponseParser, SurveyQuestion
import simulation_config as _sim_cfg

DATA_DIR = Path("data")
BATCH_DIR = Path("data/batches")


# ── helpers ───────────────────────────────────────────────────────────────────

def load_questions(wave: str):
    path = DATA_DIR / "responses" / f"survey_responses_W{wave}.json"
    with open(path) as f:
        raw = json.load(f)
    return [
        SurveyQuestion(
            question_id=q["question_id"],
            question_text=q["question_text"],
            options=[r["option"] for r in q["responses"]],
            wave=q.get("wave", f"W{wave}"),
        )
        for q in raw
    ]


def get_feature_vals(feature: str, wave: str):
    """Load unique values for a feature directly from responses.csv."""
    import pandas as pd
    path = Path("human_resp") / f"American_Trends_Panel_W{wave}" / "responses.csv"
    col = _sim_cfg.FEATURES.get(feature)
    if not col or not path.exists():
        return []
    df = pd.read_csv(path, low_memory=False)
    if col not in df.columns:
        return []
    ignored = _sim_cfg.IGNORE_VALUES.get(feature, [])
    return [str(v) for v in df[col].dropna().unique() if str(v) not in ignored]


# Triples are restricted to the original 4 features, matching the existing
# triple data generated by augment_triples.py (combinations of these only).
TRIPLE_FEATURES = ["Age", "Gender", "Race", "Income", "Political Party", "Religion"]


NEW_TRIPLE_FEATURES = ["Political Party", "Religion"]  # triples-only restricts to families touching these


def load_profiles(wave: str, include_triples: bool = False, triples_only: bool = False):
    # Build value map for every configured feature
    cats = {}
    for feature in _sim_cfg.FEATURES:
        vals = get_feature_vals(feature, wave)
        if vals:
            cats[feature] = vals

    keys = [k for k in _sim_cfg.FEATURES if k in cats]
    profiles = []
    # Singles + doubles (skipped entirely when triples_only)
    if not triples_only:
        for k in keys:
            for cat in cats[k]:
                profiles.append(DemographicProfile(features=[f"{k} {cat}"]))
        for a, b in combinations(keys, 2):
            for ca, cb in product(cats[a], cats[b]):
                profiles.append(DemographicProfile(features=[f"{a} {ca}", f"{b} {cb}"]))
    # Triples (same set as augment_triples.py for cross-model comparability)
    if include_triples:
        tkeys = [k for k in TRIPLE_FEATURES if k in cats]
        for a, b, c in combinations(tkeys, 3):
            # triples_only: emit only the new families that include Party or Religion
            if triples_only and not ({a, b, c} & set(NEW_TRIPLE_FEATURES)):
                continue
            for ca, cb, cc in product(cats[a], cats[b], cats[c]):
                profiles.append(DemographicProfile(
                    features=[f"{a} {ca}", f"{b} {cb}", f"{c} {cc}"]))
    return profiles


def request_body(model: str, system_msg: str, user_msg: str, q_batch_size: int):
    """Model-aware request body. GPT-5-family models reject `temperature`
    and `max_tokens` (use `max_completion_tokens`), and need reasoning
    effort pinned to minimal so reasoning tokens don't dominate cost."""
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_msg},
            {"role": "user",   "content": user_msg},
        ],
    }
    if model.startswith("gpt-5"):
        body["max_completion_tokens"] = 1000 if q_batch_size == 1 else q_batch_size * 60 + 500
        # gpt-5.5 supports none/low/medium/high/xhigh; older gpt-5 used "minimal"
        body["reasoning_effort"] = "none"
    else:
        body["temperature"] = 0.7
        body["max_tokens"] = 100 if q_batch_size == 1 else q_batch_size * 30 + 50
    return body


def make_custom_id(d_idx: int, q_idx: int) -> str:
    return f"d{d_idx}-q{q_idx}"


def make_batch_custom_id(d_idx: int, qb_idx: int) -> str:
    return f"d{d_idx}-qb{qb_idx}"


def parse_custom_id(custom_id: str):
    m = re.match(r"d(\d+)-q(\d+)", custom_id)
    return int(m.group(1)), int(m.group(2))


def build_multi_question_prompt(profile: DemographicProfile, questions: list) -> str:
    demo_str = ", ".join(profile.features)
    qs_block = ""
    for i, q in enumerate(questions):
        opts = "\n".join(f"    {j+1}. {o}" for j, o in enumerate(q.options))
        qs_block += f"Question {i+1}: {q.question_text}\nOptions:\n{opts}\n\n"

    return f"""Demographic Profile: {demo_str}

You are surveying exactly 1,000 individuals who fit this profile.
For EACH of the {len(questions)} questions below, distribute 1,000 individuals across the options.

{qs_block}Output a Python list of {len(questions)} lists, one per question, in order.
Each inner list contains integers summing to 1000, matching the number of options.
Output ONLY the raw Python structure. No markdown, no explanation.
Example for 2 questions with 3 and 4 options: [[300,500,200],[100,400,300,200]]"""


def parse_multi_question_response(text: str, questions: list) -> list:
    """Parse a list-of-lists response, forgivingly. Returns list of distributions
    (or None per failed item). Robust to: markdown fences, trailing prose, a
    truncated final list (keeps the complete inner lists before the cutoff), and
    inner lists summing to ~1000 (rescaled to exactly 1000). Inner lists are
    matched to questions positionally; an item only fails if it's missing or its
    integer count doesn't match that question's option count."""
    cleaned = re.sub(r"```[a-z]*\n?", "", text)
    # Each inner integer list, in order (the leading digit excludes the outer "[[").
    inner_lists = re.findall(r"\[\s*\d[\d,\s]*\]", cleaned)
    parsed = [[int(x) for x in re.findall(r"\d+", s)] for s in inner_lists]
    out = []
    for i, q in enumerate(questions):
        v = parsed[i] if i < len(parsed) else None
        if v and len(v) == len(q.options) and sum(v) > 0:
            t = sum(v)
            if t != 1000:
                v = [int(round(x * 1000 / t)) for x in v]
                v[-1] += 1000 - sum(v)
            out.append(v)
        else:
            out.append(None)
    return out


# ── submit ────────────────────────────────────────────────────────────────────

def cmd_submit(args):
    client = openai.OpenAI(api_key=args.api_key)

    print(f"Loading wave W{args.wave}...")
    questions = load_questions(args.wave)
    profiles  = load_profiles(args.wave, include_triples=args.include_triples,
                              triples_only=args.triples_only)
    print(f"  {len(questions)} questions, {len(profiles)} demographic profiles")
    print(f"  Total requests: {len(questions) * len(profiles):,}")

    BATCH_DIR.mkdir(parents=True, exist_ok=True)
    batch_input_path = BATCH_DIR / f"W{args.wave}_{args.model}_input.jsonl"

    # Find already-completed (profile, question) pairs.
    # Sort demographics so ordering differences (e.g. party-first vs age-first) don't cause misses.
    # Only SUCCESS rows count as done — error rows must be retried (this was
    # the bug that left W49 with 29-41% un-retried "Connection error" holes).
    done = set()
    out_path = DATA_DIR / "results" / args.model / f"W{args.wave}.jsonl"
    if out_path.exists():
        with open(out_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    r = json.loads(line)
                    if r.get("status") != "success":
                        continue
                    done.add((tuple(sorted(r["demographics"])), r["question_id"]))
                except Exception:
                    pass

    print(f"Writing batch input to {batch_input_path}...")
    builder = PromptBuilder()
    skipped = written = 0
    q_batch_size = args.q_batch_size

    with open(batch_input_path, "w") as f:
        for d_idx, profile in enumerate(profiles):
            # Filter out already-done questions for this profile
            pending_qs = [q for q in questions
                          if (tuple(sorted(profile.features)), q.question_id) not in done]
            skipped += len(questions) - len(pending_qs)

            # Split into batches of q_batch_size
            for qb_idx, i in enumerate(range(0, len(pending_qs), q_batch_size)):
                q_batch = pending_qs[i:i + q_batch_size]
                if q_batch_size == 1:
                    user_msg = builder.build_prompt(profile, q_batch[0])
                    max_tok = 100
                    cid = make_custom_id(d_idx, questions.index(q_batch[0]))
                else:
                    user_msg = build_multi_question_prompt(profile, q_batch)
                    max_tok = q_batch_size * 30 + 50
                    cid = make_batch_custom_id(d_idx, qb_idx)

                record = {
                    "custom_id": cid,
                    "method": "POST",
                    "url": "/v1/chat/completions",
                    "body": request_body(args.model, builder.SYSTEM_MESSAGE,
                                         user_msg, q_batch_size),
                }
                f.write(json.dumps(record) + "\n")
                written += 1

    print(f"  {written} API calls to submit ({skipped} questions already done — skipped)")

    # Split into chunks of 50k (OpenAI batch limit)
    CHUNK_SIZE = 50_000
    with open(batch_input_path) as f:
        all_lines = f.readlines()

    chunks = [all_lines[i:i+CHUNK_SIZE] for i in range(0, len(all_lines), CHUNK_SIZE)]
    print(f"Splitting into {len(chunks)} batch(es) of up to {CHUNK_SIZE:,} requests...")

    batch_ids = []
    for i, chunk in enumerate(chunks):
        chunk_path = BATCH_DIR / f"W{args.wave}_{args.model}_input_part{i+1}.jsonl"
        with open(chunk_path, "w") as f:
            f.writelines(chunk)

        print(f"  Uploading part {i+1}/{len(chunks)} ({len(chunk):,} requests, {chunk_path.stat().st_size/1024/1024:.1f} MB)...")
        with open(chunk_path, "rb") as f:
            uploaded = client.files.create(file=f, purpose="batch")

        batch = client.batches.create(
            input_file_id=uploaded.id,
            endpoint="/v1/chat/completions",
            completion_window="24h",
        )
        print(f"    Batch ID: {batch.id}  Status: {batch.status}")
        batch_ids.append(batch.id)

    print(f"\n  {len(batch_ids)} batch(es) submitted: {batch_ids}")
    print(f"\nRun this to fetch results when ready:")
    print(f"  python batch_api_runner.py fetch --wave {args.wave} --model {args.model}")

    state_path = BATCH_DIR / f"W{args.wave}_{args.model}_state.json"
    with open(state_path, "w") as f:
        json.dump({"batch_ids": batch_ids, "wave": args.wave, "model": args.model,
                   "api_key": args.api_key, "q_batch_size": args.q_batch_size,
                   "include_triples": args.include_triples,
                   "triples_only": args.triples_only,
                   "submitted_at": datetime.now().isoformat()}, f, indent=2)
    print(f"\nState saved to {state_path}")


# ── fetch ─────────────────────────────────────────────────────────────────────

def cmd_fetch(args):
    # Load state file
    state_path = BATCH_DIR / f"W{args.wave}_{args.model}_state.json"
    if not state_path.exists():
        print(f"Error: no state file found at {state_path}")
        sys.exit(1)
    with open(state_path) as f:
        state = json.load(f)
    if not args.api_key:
        args.api_key = state.get("api_key")
    if args.q_batch_size == 20:  # only override if still at default
        args.q_batch_size = state.get("q_batch_size", 20)
    print(f"q_batch_size={args.q_batch_size}")

    # Support both single batch_id (old) and batch_ids list (new)
    if args.batch_id:
        batch_ids = [args.batch_id]
    else:
        batch_ids = state.get("batch_ids") or [state.get("batch_id")]
    print(f"Found {len(batch_ids)} batch(es) to fetch.")

    client = openai.OpenAI(api_key=args.api_key)

    # Wait for all batches to complete
    result_lines = []
    for bid in batch_ids:
        print(f"\nChecking batch {bid}...")
        while True:
            batch = client.batches.retrieve(bid)
            counts = batch.request_counts
            print(f"  Status: {batch.status}  |  completed={counts.completed}  failed={counts.failed}  total={counts.total}")
            if batch.status == "completed":
                break
            if batch.status in ("failed", "expired", "cancelled"):
                print(f"  Batch {bid} did not complete successfully.")
                sys.exit(1)
            print("  Not done yet — waiting 30s...")
            time.sleep(30)

        print(f"  Downloading results for {bid}...")
        result_lines.extend(client.files.content(batch.output_file_id).text.strip().splitlines())

    print(f"\nTotal result lines: {len(result_lines):,}")
    result_content = "\n".join(result_lines)

    print("Parsing results...")
    questions   = load_questions(args.wave)
    profiles    = load_profiles(args.wave,
                                include_triples=state.get("include_triples", False),
                                triples_only=state.get("triples_only", False))
    q_batch_size = args.q_batch_size

    raw_results = {}
    for line in result_content.strip().splitlines():
        obj = json.loads(line)
        raw_results[obj["custom_id"]] = obj

    out_path = DATA_DIR / "results" / args.model / f"W{args.wave}.jsonl"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Success-only, mirroring submit's done-set so pending lists align.
    existing = set()
    if out_path.exists():
        with open(out_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    r = json.loads(line)
                    if r.get("status") != "success":
                        continue
                    existing.add((tuple(sorted(r["demographics"])), r["question_id"]))
                except Exception:
                    pass

    success = error = skipped = 0
    with open(out_path, "a") as out_f:
        for d_idx, profile in enumerate(profiles):
            pending_qs = [q for q in questions
                          if (tuple(sorted(profile.features)), q.question_id) not in existing]
            skipped += len(questions) - len(pending_qs)

            for qb_idx, i in enumerate(range(0, len(pending_qs), q_batch_size)):
                q_batch = pending_qs[i:i + q_batch_size]

                if q_batch_size == 1:
                    cid = make_custom_id(d_idx, questions.index(q_batch[0]))
                else:
                    cid = make_batch_custom_id(d_idx, qb_idx)

                obj = raw_results.get(cid)

                if obj and obj.get("response") and obj["response"]["status_code"] == 200:
                    text = obj["response"]["body"]["choices"][0]["message"]["content"].strip()
                    if q_batch_size == 1:
                        distributions = [ResponseParser.parse_response(text, len(q_batch[0].options))]
                    else:
                        distributions = parse_multi_question_response(text, q_batch)
                else:
                    distributions = [None] * len(q_batch)

                for question, dist in zip(q_batch, distributions):
                    rec = {
                        "timestamp": datetime.now().isoformat(),
                        "demographics": profile.features,
                        "question_id": question.question_id,
                        "question_text": question.question_text,
                        "options": question.options,
                        "response_distribution": dist or [],
                        "status": "success" if dist else "error",
                    }
                    out_f.write(json.dumps(rec) + "\n")
                    if dist:
                        success += 1
                    else:
                        error += 1

    total = success + error
    print(f"\nNew: {success} successful, {error} errors, {skipped} already existed")
    print(f"Results written to {out_path}")


# ── status ────────────────────────────────────────────────────────────────────

def cmd_status(args):
    client = openai.OpenAI(api_key=args.api_key)
    batch = client.batches.retrieve(args.batch_id)
    counts = batch.request_counts
    print(f"Batch   : {batch.id}")
    print(f"Status  : {batch.status}")
    print(f"Progress: {counts.completed}/{counts.total} completed, {counts.failed} failed")


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="OpenAI Batch API runner for survey simulation")
    parser.add_argument("--api-key", default=os.environ.get("OPENAI_API_KEY"), required=False)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_submit = sub.add_parser("submit")
    p_submit.add_argument("--wave",            required=True)
    p_submit.add_argument("--model",           default="gpt-4o")
    p_submit.add_argument("--api-key",         default=os.environ.get("OPENAI_API_KEY"))
    p_submit.add_argument("--q-batch-size",    type=int, default=20)
    p_submit.add_argument("--include-triples", action="store_true",
                          help="add triple profiles (Age/Gender/Race/Income combos)")
    p_submit.add_argument("--triples-only", action="store_true",
                          help="with --include-triples: emit ONLY new families touching "
                               "Political Party or Religion; skip all d1/d2/4-feat backfill")

    p_fetch = sub.add_parser("fetch")
    p_fetch.add_argument("--batch-id",      default=None)
    p_fetch.add_argument("--wave",          required=True)
    p_fetch.add_argument("--model",         default="gpt-4o")
    p_fetch.add_argument("--api-key",       default=os.environ.get("OPENAI_API_KEY"))
    p_fetch.add_argument("--q-batch-size",  type=int, default=20)

    p_status = sub.add_parser("status")
    p_status.add_argument("--batch-id", required=True)
    p_status.add_argument("--api-key",  default=os.environ.get("OPENAI_API_KEY"))

    args = parser.parse_args()

    os.chdir(Path(__file__).parent)

    # For fetch, the api key may come from the state file — check after
    if args.cmd == "submit":
        if not args.api_key:
            print("Error: provide --api-key or set OPENAI_API_KEY")
            sys.exit(1)
        cmd_submit(args)
    elif args.cmd == "fetch":
        cmd_fetch(args)  # will load key from state file if needed
    elif args.cmd == "status":
        if not args.api_key:
            print("Error: provide --api-key or set OPENAI_API_KEY")
            sys.exit(1)
        cmd_status(args)


if __name__ == "__main__":
    main()
